name: Scan topic

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      env:
        DETA_PROJECT_KEY: ${{ secrets.DETA_KEY }}
      with:
        node-version: 16.x
        cache: 'npm'
    - run: |
        yarn
        node index.js
